version: 2

models:
  - name: team_aggregates
    description: "Aggregated team performance metrics."
    columns:
      - name: team_id
        description: "Foreign key referencing dim_teams."
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
      - name: team_name
        description: "Team name."
      - name: league_name
        description: "League the team belongs to."
      - name: total_games
        description: "Total games played by the team."
      - name: wins
        description: "Total games won by the team."
      - name: losses
        description: "Total games lost by the team."
      - name: draws
        description: "Total games drawn by the team."
      - name: played_at_home
        description: "Total games played at home."
      - name: won_at_home
        description: "Total home wins."
      - name: lost_at_home
        description: "Total home losses."
      - name: drawn_games_at_home
        description: "Total home draws."
      - name: average_home_possession
        description: "Average possession when playing at home."
      - name: avg_home_goals_scored
        description: "Average goals scored at home."
      - name: avg_home_goals_conceded
        description: "Average goals conceded at home."
      - name: played_at_away
        description: "Total games played away."
      - name: won_at_away
        description: "Total away wins."
      - name: lost_at_away
        description: "Total away losses."
      - name: drawn_games_at_away
        description: "Total away draws."
      - name: average_away_possession
        description: "Average possession when playing away."
      - name: avg_away_goals_scored
        description: "Average goals scored away."
      - name: avg_away_goals_conceded
        description: "Average goals conceded away."
  - name: player_aggregates
    description: "Aggregated player performance metrics."
    columns:
      - name: player_id
        description: "Foreign key to dim_players."
        tests:
          - relationships:
              to: ref('dim_players')
              field: player_id
      - name: team_id
        description: "Foreign key to dim_teams."
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_id
      - name: total_games_played
        description: "Total games played by the player."
      - name: total_games_started
        description: "Total games started by the player."
      - name: total_minutes
        description: "Total minutes played by the player."
      - name: total_goals
        description: "Total goals scored by the player."
      - name: total_assists
        description: "Total assists by the player."
      - name: minutes_per_goal
        description: "Average minutes per goal scored."
      - name: total_games_home
        description: "Total games played at home."
      - name: total_games_away
        description: "Total games played away."
models:
  - name: manager_performance
    description: "Performance statistics for football managers."
    columns:
      - name: manager_id
        description: "Surrogate key for managers."
        tests:
          - relationships:
              to: ref('dim_managers')
              field: manager_id
      - name: manager_name
        description: "Manager's full name."
      - name: team_name
        description: "Team the manager is associated with."
      - name: league_name
        description: "League where the manager's team competes."
      - name: total_games_played
        description: "Total games managed."
      - name: total_games_won
        description: "Total games won by the manager."
      - name: total_games_drawn
        description: "Total games drawn."
      - name: total_games_lost
        description: "Total games lost."
      - name: pct_total_games_won
        description: "Percentage of games won."
      - name: pct_total_games_drawn
        description: "Percentage of games drawn."
      - name: pct_total_games_lost
        description: "Percentage of games lost."
      - name: avg_goals_scored_per_game
        description: "Average goals scored per match."
      - name: avg_goals_conceded_per_game
        description: "Average goals conceded per match."