version: 2

models:
  - name: agg_league   
    description: >
      This aggregate table summarizes team performance across all matches. 
      It includes overall statistics, home and away breakdowns, and total points 
      for each team within their respective leagues.

    columns:
      - name: TEAM_ID
        description: "Unique identifier for the team, linked to `dim_teams`."
        tests:
          - not_null
          - relationships:
              to: ref('dim_teams')
              field: TEAM_ID

      - name: TEAM_NAME
        description: "Full name of the team."
        tests:
          - not_null

      - name: Formal_League_Name
        description: "The official name of the league : English Premiership."
        tests:
          - not_null

      - name: COUNTRY_NAME
        description: "The country associated with the team's league."
        tests:
          - not_null

      - name: short_League_Name
        description: "The abbreviated version of the league name:  Premiership "
        tests:
          - not_null

      - name: GamesPlayed
        description: "Total number of matches played by the team."
        tests:
          - not_null

      - name: TotalPoints
        description: "Total points accumulated by the team (3 for a win, 1 for a draw, 0 for a loss)."
        tests:
          - not_null

      - name: Wins
        description: "Total matches won by the team."
        tests:
          - not_null

      - name: Losses
        description: "Total matches lost by the team."
        tests:
          - not_null

      - name: Draws
        description: "Total matches drawn by the team."
        tests:
          - not_null

      - name: TotalScored
        description: "Total goals scored by the team."
        tests:
          - not_null

      - name: TotalConceded
        description: "Total goals conceded by the team."
        tests:
          - not_null

      - name: HomeGamesPlayed
        description: "Total number of home matches played by the team."
        tests:
          - not_null

      - name: HomeWins
        description: "Total number of home matches won by the team."
        tests:
          - not_null

      - name: HomeLosses
        description: "Total number of home matches lost by the team."
        tests:
          - not_null

      - name: HomeDraws
        description: "Total number of home matches drawn by the team."
        tests:
          - not_null

      - name: HomeScored
        description: "Total goals scored by the team in home matches."
        tests:
          - not_null

      - name: HomeConceded
        description: "Total goals conceded by the team in home matches."
        tests:
          - not_null

      - name: HomePoints
        description: "Total points earned in home matches."
        tests:
          - not_null

      - name: AwayGamesPlayed
        description: "Total number of away matches played by the team."
        tests:
          - not_null

      - name: AwayWins
        description: "Total number of away matches won by the team."
        tests:
          - not_null

      - name: AwayLosses
        description: "Total number of away matches lost by the team."
        tests:
          - not_null

      - name: AwayDraws
        description: "Total number of away matches drawn by the team."
        tests:
          - not_null

      - name: AwayScored
        description: "Total goals scored by the team in away matches."
        tests:
          - not_null

      - name: AwayConceded
        description: "Total goals conceded by the team in away matches."
        tests:
          - not_null

      - name: AwayPoints
        description: "Total points earned in away matches."
        tests:
          - not_null

  - name: agg_player
    description: >
      This aggregate table summarizes player performance across matches.
      It includes total match involvements, goals, assists, cards, minutes played, 
      efficiency metrics (per 90 mins), and impact metrics across different roles.

    columns:
      - name: player_id
        description: "Unique identifier for the player, linked to `dim_players`."
        tests:
          - not_null
          - relationships:
              to: ref('dim_players')
              field: player_id

      - name: Player_name
        description: "Full name of the player."
        tests:
          - not_null

      - name: TEAM_ID
        description: "Unique identifier for the team, linked to `dim_teams`."
        tests:
          - not_null
          - relationships:
              to: ref('dim_teams')
              field: TEAM_ID

      - name: TEAM_NAME
        description: "Full name of the team."
        tests:
          - not_null

      - name: league_name
        description: "Name of the league in which the player's team competes."
        tests:
          - not_null

      - name: Country_name
        description: "Country where the player's league is based."
        tests:
          - not_null

      - name: SHORT_NAME
        description: "Abbreviated version of the team's name."
        tests:
          - not_null

      - name: Total_YellowCards
        description: "Total yellow cards received by the player."
        tests:
          - not_null

      - name: Total_RedCards
        description: "Total red cards received by the player."
        tests:
          - not_null

      - name: Total_Goals
        description: "Total goals scored by the player."
        tests:
          - not_null

      - name: Total_Assists
        description: "Total assists made by the player."
        tests:
          - not_null

      - name: Total_MinutesPlayed
        description: "Total minutes played by the player across all matches."
        tests:
          - not_null

      - name: Total_Squads_Made
        description: "Total number of match squads the player was included in."
        tests:
          - not_null

      - name: Total_Match_Involvements
        description: "Total matches where the player was involved as a Starter or Sub."
        tests:
          - not_null

      - name: Goals_Per_90
        description: "Goals scored per 90 minutes played."
        tests:
          - not_null

      - name: Assists_Per_90
        description: "Assists per 90 minutes played."
        tests:
          - not_null

      - name: Goal_Contribution_Per_90
        description: "Total goal contributions (Goals + Assists) per 90 minutes played."
        tests:
          - not_null

      - name: Cards_Per_90
        description: "Total cards (yellow + red) received per 90 minutes played."
        tests:
          - not_null

      - name: Pct_Goals_When_Started
        description: "Percentage of the player's goals scored when starting."
        tests:
          - not_null

      - name: Pct_Goals_When_Sub
        description: "Percentage of the player's goals scored when coming off the bench."
        tests:
          - not_null

      - name: Pct_Goals_When_Squad
        description: "Percentage of the player's goals scored when not starting or subbed in."
        tests:
          - not_null

  - name: agg_manager
    description: >
      This aggregate table summarizes manager performance across matches. 
      It includes total games played, wins, losses, and draws, along with 
      home and away performance breakdowns. 

    columns:
      - name: manager_id
        description: "Unique identifier for the manager, linked to `dim_managers`."
        tests:
          - not_null
          - relationships:
              to: ref('dim_managers')
              field: manager_id

      - name: manager_name
        description: "Full name of the manager."
        tests:
          - not_null

      - name: team_id
        description: "Unique identifier for the team managed, linked to `dim_teams`."
        tests:
          - not_null
          - relationships:
              to: ref('dim_teams')
              field: team_id

      - name: total_games_played
        description: "Total number of matches the manager has led the team."
        tests:
          - not_null

      - name: games_won_pct
        description: "Percentage of games won by the manager."
        tests:
          - not_null

      - name: games_lost_pct
        description: "Percentage of games lost by the manager."
        tests:
          - not_null

      - name: games_drawn_pct
        description: "Percentage of games drawn by the manager."
        tests:
          - not_null

      - name: home_games_played
        description: "Total number of home matches managed."
        tests:
          - not_null

      - name: home_games_won_pct
        description: "Percentage of home matches won by the manager."
        tests:
          - not_null

      - name: home_games_lost_pct
        description: "Percentage of home matches lost by the manager."
        tests:
          - not_null

      - name: home_games_drawn_pct
        description: "Percentage of home matches drawn by the manager."
        tests:
          - not_null

      - name: away_games_played
        description: "Total number of away matches managed."
        tests:
          - not_null

      - name: away_games_won_pct
        description: "Percentage of away matches won by the manager."
        tests:
          - not_null

      - name: away_games_lost_pct
        description: "Percentage of away matches lost by the manager."
        tests:
          - not_null

      - name: away_games_drawn_pct
        description: "Percentage of away matches drawn by the manager."
        tests:
          - not_null
